### ISSUE TITLE
ffmpeg exited with code 1: Error opening filters!

### ISSUE THREAD

**Issue by davyzhen** [h2non/videoshow#18]
How to fix this ?

Here is my FFmpeg configuration: 

--prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-frei0r --enable-gnutls --enable-libass --enable-libcdio --enable-libcelt --enable-libdc1394 --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopencv --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect

Thanks

**Comment by h2non** [comment]
Could you share the code you are using? This is probably due to a bad video filter definition

**Comment by davyzhen** [comment]
After reinstall libx264, the error gone.
I can create video through the command-line. 
But i have a new problem, the created video doesn't have sound.

Here is command i use: 
# videoshow -c config.json --audio aurore.mp3 video.mp4  

Here is config.json: 
{
  "output": "video.mp4",
  "options": {
    "fps": 25,
    "loop": 5,
    "transition": true,
    "transitionDuration": 1,
    "videoBitrate": 1280,
    "videoCodec": "libx264",
    "size": "720x?",
    "audioBitrate": "128k",
    "audioChannels": 2,
    "format": "mp4"
  },
  "images": [
    "./img/img001.jpg",
    "./img/img002.jpg",
    "./img/img003.jpg",
    "./img/img004.jpg",
    "./img/img005.jpg"

  ]
}

Thanks,

**Comment by h2non** [comment]
I've just fixed a minor issue with version `0.1.8`. Update `videoshow` and try it again!
```
npm install videoshow --force
```

**Comment by davyzhen** [comment]
Installed new version, there is no WARN message during install.
However, the video created still don't have sound and caption  : (

**Comment by h2non** [comment]
Forget about the `npm` warning. It hasn't any relationship with the issue.

Please, be sure you've updated correctly the package. Test it with:
```
videoshow --version
```
You should get `0.1.9`

I created a video without any problem from CLI with the following config:
```
{
 "options": {
 "fps": 25,
 "loop": 5,
 "captionDelay": 1000,
 "useSubRipSubtitles": false,
 "subtitleStyle": {
   "Fontname": "Verdana",
   "Fontsize": "24",
   "PrimaryColour": "11861244"
 },
 "transition": true,
 "transitionDuration": 3,
 "videoBitrate": 1024,
 "videoCodec": "libx264",
 "size": "640x?",
 "audioBitrate": "128k",
 "audioChannels": 2,
 "format": "mp4"
},
"images": [
  { "path": "./test/fixtures/step_1.png", 
  "caption": "This is a sample subtitle",
  "loop": 10 },
  { "path": "./test/fixtures/step_2.png", 
  "caption": "This is a subtitle", 
  "loop": 10 },
  { "path": "./test/fixtures/step_3.png", 
   "caption": "This is a test"
   }
 ]
}
```

Test command:
```
videoshow --config config.json video.mp4
```

**Comment by davyzhen** [comment]
After install new version 0.1.9, Error shows again 
Error: ffmpeg exited with code 1: Error opening filters!

Here is debug information: 

ffmpeg process started: ffmpeg -i /tmp/videoshow-2ca1983b-ffd1-4b5e-b3c8-f263c8ab6293 -i /tmp/videoshow-289ea9fd-f012-4f4c-b0e9-3467804cb8ab -i /tmp/videoshow-746ef063-a9bc-4399-ad0b-7f37c2fd68d3 -y -filter_complex concat=n=3:v=1:a=0 video.mp4

ffmpeg process started: ffmpeg -i /tmp/videoshow-0cf7cf4b-588f-49dc-b8f1-2a101e8be7cc -i aurore.mp3 -y -b:a 128k -ac 2 -r 25 -b:v 1024k -vcodec libx264 -filter:v scale=w=640:h=trunc(ow/a/2)*2 -f mp4 -map 0:0 -map 1:0 -t 25 -af afade=t=in:ss=0:st=0:d=3 -af afade=t=out:st=22:d=3 -vf subtitles='/tmp/videoshow-43d8e159-5535-4cc0-b2cc-8043a9e946ad.ass' video.mp4

Error: ffmpeg exited with code 1: Error opening filters!

at ChildProcess.<anonymous> (/usr/lib/node_modules/videoshow/node_modules/fluent-ffmpeg/lib/processor.js:167:22)
at ChildProcess.emit (events.js:98:17)
at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by h2non** [comment]
For some reason the filter is not working fine. This is my current ffmpeg compilation flags (using OSX):

```
--enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-aacenc --enable-libass --enable-ffplay --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-libopus --enable-frei0r --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags='-I/usr/local/Cellar/openjpeg/1.5.1_1/include/openjpeg-1.5 ' --enable-vda
```

Could you try rendering the video without subtitles?

**Comment by h2non** [comment]
Any new about this?

**Comment by davyzhen** [comment]
Too busy recently, I didn't test it yet.Will let you know in next week. Best Regards,
Davy

Date: Fri, 24 Apr 2015 10:21:00 -0700

**Comment by h2non** [comment]
FYI I'm recently using `videoshow` in a Heroku instance and it's working fine. 

You can use the following buildpack which install a static build of ffmpeg with most of the third-party libraries bindings:
https://github.com/h2non/heroku-buildpack-ffmpeg2.git

You can download the static builds from here:
http://johnvansickle.com/ffmpeg/

**Comment by h2non** [comment]
Deprecated. Closing

**Comment by deepakpapola** [comment]
i have following error using videoshow 

 Error: ffmpeg exited with code 1: Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #4:0
Conversion failed!

    at ChildProcess.<anonymous> (E:\node\node test\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
ffmpeg stderr: undefined

**Comment by suleymanakgul** [comment]
At first thanks for this perfect work.
I also faced same problem Error reinitializing filters!, at processor.js line 182.
I am a windows user and downloaded ffmpeg static build from url of https://ffmpeg.zeranoe.com/builds/ and images i used are same size.
Problem occures when i added caption to an image, or subtitle. Could you please help me to get rid of this ?

Details :
Error: ffmpeg exited with code 1: Error opening filters!
at ChildProcess. (C:\Users\Samaritan\node_modules\fluent-ffmpeg\l
ib\processor.js:182:22)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
ffmpeg stderr: undefined

**Comment by russjfreeman** [comment]
I'm having the same problem, using 0.1.11. Any chance of a fix for this?

**Comment by suleymanakgul** [comment]
I could not solve problem but i solved by using another ffmpeg command with ass file without using this project directly. if you want to use here is the link : https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo
